server:
  port: 8082
  servlet:
    contextPath: /CarPartsShop
spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/carparts?user=web_user
    driverClassName : com.mysql.cj.jdbc.Driver