server:
  port: 8082
  servlet:
    contextPath: /CarPartsShop
spring:
  datasource:
    password: mssqlPWD1*
    url: jdbc:sqlserver://localhost:1433;user=sa;databaseName=CarPartsShop;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver